In [ ]:
import torch
import torch.nn as nn

In [ ]:
MyNet = nn.Sequential(
  nn.Linear(3, 1),
  nn.ReLU(),
)
print(MyNet)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): ReLU()
)


### Prepare input data

In [ ]:
lstX = [[1,2,3],[4,5,6],[7,8,9]]
tensorX = torch.FloatTensor(lstX)
print(tensorX, "\n", tensorX.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 
 torch.Size([3, 3])


In [ ]:
for name, params in MyNet.named_parameters():
    if params.requires_grad:
        print(name, params.data)

0.weight tensor([[-0.1287, -0.3801,  0.3944]])
0.bias tensor([-0.4094])


1. Use Pytorch matrix multiplcation: tensor1.mm(tensor2) to calculate answer

In [ ]:
W0 = MyNet[0].weight
print(W0, W0.shape)

Parameter containing:
tensor([[-0.1287, -0.3801,  0.3944]], requires_grad=True) torch.Size([1, 3])


In [ ]:
# transpose of W0
W0t = torch.transpose(W0, 1, 0)
print(W0t, W0t.shape)

tensor([[-0.1287],
        [-0.3801],
        [ 0.3944]], grad_fn=<TransposeBackward0>) torch.Size([3, 1])


In [ ]:
tensorX.mm(W0t)

tensor([[ 0.2942],
        [-0.0492],
        [-0.3925]], grad_fn=<MmBackward0>)

In [ ]:
tensorX.mm(W0t)+MyNet[0].bias

tensor([[-0.1153],
        [-0.4586],
        [-0.8020]], grad_fn=<AddBackward0>)

In [ ]:
relu = nn.ReLU()

In [ ]:
relu(tensorX.mm(W0t)+MyNet[0].bias)

tensor([[0.6927],
        [1.8030],
        [2.9133]], grad_fn=<ReluBackward0>)

2. Try different activation function

In [ ]:
Sigmoid = nn.Sigmoid()
Sigmoid(tensorX.mm(W0t)+MyNet[0].bias)

In [ ]:
Tanh = nn.Tanh()
Tanh(tensorX.mm(W0t)+MyNet[0].bias)