In [ ]:
import torch
import torch.nn as nn

In [ ]:
MyNet = nn.Sequential(
  nn.Linear(3, 1),
  nn.ReLU(),
)
print(MyNet)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): ReLU()
)


### Test Activation function

In [ ]:
# test Relu activatio function
relu = nn.ReLU()
x = torch.FloatTensor([-0.23, -56.7, 34])
relu(x)

tensor([ 0.,  0., 34.])

### 1 Dimention Neuron

In [ ]:
lstX_1 = [[1,2,3]]
tensorX_1 = torch.FloatTensor(lstX_1)
print(tensorX_1, "\n", tensorX_1.shape)

tensor([[1., 2., 3.]]) 
 torch.Size([1, 3])


In [ ]:
for name, params in MyNet.named_parameters():
    if params.requires_grad:
        print(name, params.data)

0.weight tensor([[ 0.0970, -0.1254,  0.5721]])
0.bias tensor([0.5301])


1. Use Pytorch matrix multiplcation: tensor1.mm(tensor2) to calculate answer

$W0=(w1, w2, w3)$

In [ ]:
W0 = MyNet[0].weight
print(W0, W0.shape)

Parameter containing:
tensor([[ 0.0970, -0.1254,  0.5721]], requires_grad=True) torch.Size([1, 3])


$W0T=(w1, w2, w3)T$

In [ ]:
# transpose of W0
W0t = torch.transpose(W0, 1, 0)
print(W0t, W0t.shape)

tensor([[ 0.0970],
        [-0.1254],
        [ 0.5721]], grad_fn=<TransposeBackward0>) torch.Size([3, 1])


$x*W0T=(x1, x2, x3)(w1, w2, w3)T$

In [ ]:
tensorX_1.mm(W0t)

tensor([[1.5626]], grad_fn=<MmBackward0>)

$x*W0T + b=(x1, x2, x3)(w1, w2, w3)T+b$

In [ ]:
tensorX_1.mm(W0t)+MyNet[0].bias

tensor([[2.0927]], grad_fn=<AddBackward0>)

$Relu(x*W0T + b)=Relu((x1, x2, x3)(w1, w2, w3)T+b)$

In [ ]:
relu(tensorX_1.mm(W0t)+MyNet[0].bias)

tensor([[2.0927]], grad_fn=<ReluBackward0>)

### 3 Dimention Neuron

In [ ]:
lstX_2 = [[1,2,3],[4,5,6],[7,8,9]]
tensorX_2 = torch.FloatTensor(lstX_2)
print(tensorX_2, "\n", tensorX_2.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 
 torch.Size([3, 3])


1. Use Pytorch matrix multiplcation: tensor1.mm(tensor2) to calculate answer

$x*W0T + b=(x1, x2, x3)(w1, w2, w3)T+b$

In [ ]:
tensorX_2.mm(W0t)+MyNet[0].bias

tensor([[2.0927],
        [3.7238],
        [5.3550]], grad_fn=<AddBackward0>)

$Relu(x*W0T + b)=Relu((x1, x2, x3)(w1, w2, w3)T+b)$

In [ ]:
relu(tensorX_2.mm(W0t)+MyNet[0].bias)

tensor([[2.0927],
        [3.7238],
        [5.3550]], grad_fn=<ReluBackward0>)